// Generated by CoffeeScript 1.6.3
var params={},
  filemon = require('./filemon');
var copyfilemon = function(config) {params = config;}
copyfilemon.prototype.brunchPlugin = true;
copyfilemon.prototype.type='javascript';
copyfilemon.prototype.extension='js';


copyfilemon.prototype.onCompile = function(data, path, callback) {
  Object.keys(params.copyfilemon).forEach(function(key){
    var dir = key;
    var files = params.copyfilemon[key];
    if(typeof files === 'string'){
      filemon.copyFolderRecursiveAsync(files, 'public/'+dir);
    }else{
      var i =0, l = files.length;
      console.log(dir, files, '¡¡¡¡¡');

      for(i;i<l;i++)
        filemon.copyFolderRecursiveAsync(files[i], 'public/'+dir);
    }

  });
};

module.exports = copyfilemon;
