// Generated by CoffeeScript 1.6.3
var params={},
  filemon = require('./filemon');
var copyfilemon = function(config) {params = config;}
copyfilemon.prototype.brunchPlugin = true;
copyfilemon.prototype.type='javascript';
copyfilemon.prototype.extension='js';


copyfilemon.prototype.onCompile = function(data, path, callback) {

  Object.keys(params.plugins.copyfilemon).forEach(function(key){
    var dir = key;
    var files = params.plugins.copyfilemon[key];
    if(typeof files === 'string'){
      filemon.copyFolderRecursiveAsync(files, params.paths.public + '/'+dir);
    }else{
      var i =0, l = files.length;
      for(i;i<l;i++)
        filemon.copyFolderRecursiveAsync(files[i], params.paths.public + '/'+dir);
    }

  });
};

module.exports = copyfilemon;
